version: "3.9"

services:
  # Наш бэкенд (агент на Groq)
  backend:
    build:
      context: ./backend  # Путь к папке, где лежит Dockerfile
    container_name: hacknu_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB__DB_HOST=postgres-db
      - REDIS__REDIS_HOST=redis
      - MEILISEARCH__HOST=http://meilisearch:7700
    depends_on:
      redis:
        condition: service_started
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS__REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  redis_data:
