version: "3.9"

services:
  # Наш бэкенд (агент на Groq)
  backend:
    build:
      context: ./backend  # Путь к папке, где лежит Dockerfile
    container_name: hacknu_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB__DB_HOST=postgres-db
      - REDIS__REDIS_HOST=redis
      - MEILISEARCH__HOST=http://meilisearch:7700
    depends_on:
      postgres-db:
        condition: service_started
      redis:
        condition: service_started
      meilisearch:
        condition: service_healthy

  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB__DB_USER}
      POSTGRES_PASSWORD: ${DB__DB_PASSWORD}
      POSTGRES_DB: ${DB__DB_NAME}
    ports:
      - "${DB__DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS__REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH__MEILI_MASTER_KEY}
      - MEILI_HTTP_ADDR=0.0.0.0:7700  # Исправлено с 770 на 7700
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  meili_data: